### ISSUE TITLE
Ensure Visual Studio compatibility

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3900]
**Reported by NickMcConnell on 15 Feb 2015 20:14 UTC**
Things like
```
static struct init_module arrays_module = {
.name = "arrays",
.init = init_arrays,
.cleanup = cleanup_arrays
};
```
are too confusing for it.

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 15 Feb 2015 20:15 UTC**

**Comment by angband-import** [comment]
**Comment by myshkin on 15 Feb 2015 20:52 UTC**
As I suggested in IRC, a move to style like 

```
static struct init_module arrays_module = {
    /* .name = */    "arrays",
    /* .init = */    init_arrays,
    /* .cleanup = */ cleanup_arrays
};
```

might be a good compromise between compatibility and readability. It does make for more work and possible confusion if struct members change, though.

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 7 Jun 2015 07:07 UTC**
Kicking this one to future

**Comment by Eastwind921** [comment]
The code compiles for VS today without any changes for this issue - so I assume there are no uses of this struct initialization feature in Angband today, except perhaps in platform-specific code for non-windows targets. So what's the bug? The real gripe here that VS doesn't support this feature - which is due to the C front end being ancient crufty legacy software written in the 1980's that MS doesn't want to have to touch if its at all possible to avoid it.  I feel confident they aren't *ever* going to add support for this syntactic sugar to C. 

IMHO Visual Studio should be considered a 'supported compiler' for Angband, and since VS C doesn't support this feature, that means the feature can't be used in Angband, because you have to code to the greatest-common-denominator supported. If someday a decision is made to convert Angband from C to C++, and the VS compiler supports this feature by then and all the other compilers that Angband considers 'supported compilers' support the feature, then it could be used.

**Comment by backwardsEric** [comment]
The designated initializer syntax in .c files does compile with Visual Studio 2019's cl.exe when compiling them as C code (i.e. with the /TC switch).  I haven't found a definitive reference in Microsoft's documentation that says when that capability was added, but some things suggest that it's been that way since Visual Studio 2013.  As such, marking this as "works for me" since Microsoft was kind enough to fix it for us.

With a GitHub workflow that compiles everything using Visual Studio toolchain, we're in a position to find these sorts of incompatibilities.  Currently, there aren't any, at least when using Visual Studio 2019.
