### ISSUE TITLE
Disconnected dungeon

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4080]
**Reported by NickMcConnell on 7 Jun 2017 12:48 UTC**
Example: http://angband.oook.cz/forum/showpost.php?p=121420&postcount=94

**Comment by backwardsEric** [comment]
That particular example was from a period when the new level types (lair, gauntlet, and hard centre) were enabled briefly.  Given that several changes were made to those levels since then, and there haven't been recent reports of trouble (the most recent was a problem with the gauntlet levels reported by MattB, http://angband.oook.cz/forum/showpost.php?p=152558&postcount=19 ), perhaps mark this one as done and let any new disconnection problems get their own issue(s)?

**Comment by NickMcConnell** [comment]
Agreed.
