### ISSUE TITLE
Fully known object showing ? in player display

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4190]
**Reported by NickMcConnell on 4 Oct 2019 21:53 UTC**
Likely something to do with curses, see http://angband.oook.cz/forum/showpost.php?p=140314&postcount=192

**Comment by angband-import** [comment]
**Attachment from NickMcConnell on 4 Oct 2019 21:53 UTC**
Savefile
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_2130_GIT_4190/pot

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 4 Oct 2019 21:53 UTC**

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 12 Oct 2019 23:21 UTC**

**Comment by NickMcConnell** [comment]
This is an obscure issue with how knowledge propagates to "curse objects"; in particular, calling object_non_curse_runes_known() on the curse object for the "chilled to the bone" curse returns false, because the known object for the curse object has not acquired the element properties for Fire and Cold.

The tricky part here is working out whether it should have acquired those properties, or whether the function shoudl return true just because it's a curse object and it should know what it's doing.

**Comment by NickMcConnell** [comment]
Answer - the former.
