### ISSUE TITLE
Game hang on targeting

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4217]
**Reported by NickMcConnell on 4 Oct 2019 22:46 UTC**
See http://angband.oook.cz/forum/showthread.php?t=9549

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 12 Oct 2019 23:21 UTC**

**Comment by NickMcConnell** [comment]
Seems like this will be in ui-target.c, probably target_set_interactive().

**Comment by backwardsEric** [comment]
In a case where this happened to me (Angband post 4.2.0 but custom compiled with a modified OS X front end) the sequence of events in the infinite loop were:

1) Start at top of while(!done) loop in target_set_interactive().
2) flag and help are false so skip to the call to project_path() which returns 2.
3) mode is 2 so skip the draw_path() call.
4) Enter target_set_interactive_aux() with values for y (254) and x (123) that are out of bounds for the cave (height = 63, width = 192).
5) Enter the while(1) loop in target_set_interactive_aux() but bail out at the square_in_bounds() check.  The event returned to target_set_interactive() is the one set after the "paranoia" comment: type = EVT_KBD, key.code = ' ', key.mods = 0.
6) Back in target_set_interactive(), path_drawn is false so skip load_path() and proceed to analyze the event.  Skip to the switch statement on press.key.code.  Since it is ' ' nothing further is done within the switch statement.  Since the direction is 0 from the initialization after the skipped load_path() call, no adjustment is made to the position and go back to (1).

I don't know what put the coordinate values out of bounds to start with.  A different value for the fallback event in target_set_interactive_aux() (perhaps key.code = 'p' to recenter on the player) could allow for a graceful recovery from the earlier error in this case.

**Comment by NickMcConnell** [comment]
Awesome, I hadn't worked out what was causing this.

**Comment by NickMcConnell** [comment]
OK, with the adjustment from that pull request, I'm going to set an upcoming commit which implements that "centre on player" suggestion to close this.
