### ISSUE TITLE
Mac port graphics and other issues

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4231]
**Reported by NickMcConnell on 5 Nov 2019 20:24 UTC**
Mac port doesn't have scalable tiles (see http://angband.oook.cz/forum/showthread.php?t=7316), and also seems to be laggy and unstable.

**Comment by NickMcConnell** [comment]
I believe pretty much everything apart from the scalable tiles has been done by backwardsEric, so I'm going to set this to Ongoing.

**Comment by rubjo** [comment]
Testing scaleable tiles: seems to work really well, thanks @backwardsEric!

Especially Shockbolt tiles (which as far as I remember are the largest and probably most resource-hungry) makes everything a bit laggy. Hard to do anything about, maybe?

**Comment by backwardsEric** [comment]
It's good to hear it worked for you.  Performance testing - which I plan to do as part of seeing if a fairly simple change to reduce the amount redrawn is useful - should help locate where the bottlenecks are.  If it's a memory bandwidth issue, getting the tile set image to reside in the graphics hardware would likely be the path forward, but that probably requires something like SpriteKit (available since 10.9) or Metal (available since 10.11) since OpenGL is deprecated.

**Comment by NickMcConnell** [comment]
I'm calling this one, no thanks to me :)
