### ISSUE TITLE
Avavir vs. Huorn

### ISSUE THREAD

**Issue by Sphara77** [angband/angband#4361]
Scythe Avavir has both fire and cold brand but it always chooses cold brand against fire-vulnerable huorn.

**Comment by backwardsEric** [comment]
From what I saw in the code, player melee or launched/thown missile attacks don't use the element vulnerability flag when computing damage. That vulnerability flag is currently used when computing damage from projection effects like spells and magical devices and for melee attacks between monsters.

I didn't try to track down if omitting the element vulnerability flag from the player's melee/ranged damage was an intentional decision or a bug.

 #4198 is related to the issue.

**Comment by NickMcConnell** [comment]
Yes, this is actually a duplicate of #4198, so I'll close it.
