### ISSUE TITLE
Adjustment to magic device fail formula

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#4663]
See [this thread](http://angband.oook.cz/forum/showthread.php?t=10594).

**Comment by backwardsEric** [comment]
As a first round of brainstorming, assume a linear relationship between device level (i.e. difficulty) - device skill and the failure rate with the same minimum (1%) and maximum (75%) failure rates as now.  So f = m * (d - s) + b where m and b are parameters that can be tuned.  If a failure rate for d=20 (staff of teleportation, wand of teleport level) and a mediocre skill (s=30) is fixed at 20%, then are down to one tunable parameter since b = 10 * m + 20.  Plotting the failure rate as a function of m, the remaining tunable parameter, for different combinations of device level and device skill gives this (assuming lowest skill of 0 and highest of 140; with device levels between 5 and 95):

![linear_fail_rate](https://user-images.githubusercontent.com/55062581/119708454-060a6c80-be11-11eb-88a7-5c5bf97518a0.png)

To get high failure rates for poor skill requires large values of m, but that also drives down the failure rate for high skill.  It looks like that's not going to satisfy PowerWyrm's and tangar's requirements.

**Comment by backwardsEric** [comment]
Another alternative is to use a formula that is similar to the one already in place:  f = (m * (d - s) + o) / (s - d + p).  To avoid division by zero, p has to be more than maximum device level - minimum skill and, using the smallest possible value, maximum device level - minimum skill + 1, gives the greatest sensitivity of the failure rate to d - s.  That leaves m and o to tune.  If the failure rate of 20% for skill = 30 and device level = 20 is used as an anchor point have o = 20 * (p + 10) + 10 * m.  The attached plot (using 96 for p) shows how the failure rate varies as a function of m for different combinations of d and s.

![modified_current_fail_rate](https://user-images.githubusercontent.com/55062581/119725270-9dc58600-be24-11eb-98dd-73802834e740.png)

Like the linear model, larger values of m are needed to get high failure rates for poor skill and those also drive down the failure rates for high skill.  Because of the s - d term in the numerator however, it becomes easier to get the high failure rates so this, with the appropriate choice of m, could be more usable.

**Comment by NickMcConnell** [comment]
Thanks, I was just starting to come to grips with this.

I'd suggest posting this analysis to the relevant forum thread - it seems to me to fit the end value requirements, but I don't know if they'll like the complexity 😁

**Comment by backwardsEric** [comment]
Another family of options is to take function with a sigmoidal shape, https://en.wikipedia.org/wiki/Sigmoid_function , and scale and offset it so the result is 0 to 100.  I tried 50 * (1 + (m * (d - s) + b)^p / (1 + abs(m * (d - s) + b)^p)) with p = 1.  I didn't work out the formulas for relating b to m for a choice of anchor point and p.  Using these combinations of m and b (which correspond to the same anchor point in the previous models: device level = 20, device skill = 30, failure rate = 20%) ((0.00025, -1.4975), (0.0005, -1.495), (.001, -1.49), (0.0025, -1.475), (0.005, -1.45) , (.01, -1.4), (.025, -1.25), (.05, -1.0), (.1, -0.5), (.2, 0.5)) gave this result for the failure rates with the same combinations of device level and device skill as in the previous models.

![sigmoid1_fail_rate](https://user-images.githubusercontent.com/55062581/119747512-bf843480-be47-11eb-8292-48922f41f400.png)

For m = 0.1, that gives quite high failure rates for the low and mediocre skill levels.  Though, the high skill case is having a harder time reaching the minimum failure rate.

**Comment by backwardsEric** [comment]
Here's some plots to document how Angband 4.2.2 currently handles the failure rate for devices.  Since intelligence does not have  a particularly large impact on the device skill (device skill at the maximum possible intelligence is 13 points better than the skill at the worst possible intelligence), all of these plots are done versus character level with an assumption about how a typical character gains intelligence between level 1 and level 50.  With those assumptions, the device skill as a function of character level looks like this:

![devskill_by_level](https://user-images.githubusercontent.com/55062581/121265463-b050ae00-c86d-11eb-8030-db2f77e610d0.png)

Then the failure rates for a selection of utility devices (from easier to harder to use) looks like this:

![failrate-4-2-2-lightstaff](https://user-images.githubusercontent.com/55062581/121265546-d2e2c700-c86d-11eb-9e1d-27591955b3d8.png)
![failrate-4-2-2-towand](https://user-images.githubusercontent.com/55062581/121265602-e857f100-c86d-11eb-979d-ccafd8c512c3.png)
![failrate-4-2-2-speedstaff](https://user-images.githubusercontent.com/55062581/121265628-f148c280-c86d-11eb-9799-1b3959952dc6.png)
![failrate-4-2-2-mmrod](https://user-images.githubusercontent.com/55062581/121265658-fc9bee00-c86d-11eb-8551-c4f3694061ec.png)
![failrate-4-2-2-speedrod](https://user-images.githubusercontent.com/55062581/121265683-03c2fc00-c86e-11eb-9afe-d37fb2f0a22a.png)

For a selection of (mostly) single-target damage wands, the (1 - failure rate) * device damage boost * average damage not accounting for the failure rate and damage boost looks like this:

![wanddam-4-2-2-htw](https://user-images.githubusercontent.com/55062581/121265851-58667700-c86e-11eb-9553-09da56a9aff3.png)
![wanddam-4-2-2-dp](https://user-images.githubusercontent.com/55062581/121265864-5e5c5800-c86e-11eb-9998-03e9431feebd.png)
![wanddam-4-2-2-hr](https://user-images.githubusercontent.com/55062581/121265877-661bfc80-c86e-11eb-8007-3833aa1baa0f.png)
![wanddam-4-2-2-gm](https://user-images.githubusercontent.com/55062581/121265898-6e743780-c86e-11eb-9ac4-1945da1a56e6.png)

**Comment by backwardsEric** [comment]
Look at the arctan(x) functional form suggested by Pete Mack, and two other sigmoid functions, 1/(1+e^-x), and x/(1+abs(x)) to see which is the most promising for use a possible replacement.  In all, take x to be p * (device_skill - device_level) + q where p and q are tunable parameters and scale and offset the curves so the result will be between .01 and .75 (4.2.2's bounds on the failure rate).  Reduce the two tunable parameters to one by having the new form reproduce 4.2.2's failure rate of .127 for device_skill equal to 31 and device_level equal to 20 (essentially a level 30 half-troll warrior using a wand of teleport other or a staff of teleportation).  The failure rates for a wand of teleport other for some coarsely selected values of p (referred to as scale in the legend), look like this for arctan():

![frtune-arctan-htw-tow](https://user-images.githubusercontent.com/55062581/121266966-4980c400-c870-11eb-983e-dcac5202919a.png)
![frtune-arctan-gm-tow](https://user-images.githubusercontent.com/55062581/121266990-53a2c280-c870-11eb-8b1c-9dd64cde2b2d.png)

Look like this for the logistic function, 1/(1+e^-x):

![frtune-logistic-htw-tow](https://user-images.githubusercontent.com/55062581/121267048-6ddca080-c870-11eb-92ba-245bad741a37.png)
![frtune-logistic-gm-tow](https://user-images.githubusercontent.com/55062581/121267056-70d79100-c870-11eb-82b4-522bd146eeeb.png)

And look like this for x/(1+abs(x)):

![frtune-eb-htw-tow](https://user-images.githubusercontent.com/55062581/121267104-851b8e00-c870-11eb-80e0-5dcf09b5e5e2.png)
![frtune-eb-gm-tow](https://user-images.githubusercontent.com/55062581/121267117-89e04200-c870-11eb-81a2-cc47d7c92edc.png)

For the scale choices shown, all of the proposals increase the failure rate relative to 4.2.2 for low-level half-trolls, but slightly boost their chances at high levels.  For gnome mages, the lower levels sometimes benefit compared to 4.2.2 from a lower failure rate, but the higher levels suffer from slightly higher failure rates.

The x/(1+abs(x)) has the slight advantage that it could be more easily implemented in integer arithmetic.

**Comment by backwardsEric** [comment]
The above were for functions where the right side of the transition is essentially the left side flipped about both the horizontal and vertical axes.  Pete Mack proposed, http://angband.oook.cz/forum/showpost.php?p=153490&postcount=19 , using asymmetric forms where the side of the transition for low skill has a less sharp fall off.  Here are the results for using failure rate = .75 - .74/(2+log(1-x)) for x < 0 and failure rate = .01 + .74 / (2 + x) when x >= 0; x is p * (device_skill - device_level) + q where p and q are tunable parameters.  That is similar to Pete Mack's proposal.  I replaces log(-x) with log(1-x) so the interval of -1 < x < 0 is handled easily and altered the asymptotes to match up with 4.2.2's bounds of .01 and .75 on the failure rate.  For tuning, chose q such that the failure rate for device_skill=31 and device_level=20 was .127.

Tuning p by looking at the failure rate for a wand of teleport other gives:
![frtune-pml-htw-tow](https://user-images.githubusercontent.com/55062581/121429560-e6ecfe00-c92b-11eb-9fa3-c0215146fe1a.png)
![frtune-pml-gm-tow](https://user-images.githubusercontent.com/55062581/121429588-eeaca280-c92b-11eb-98fe-040947234ec7.png)

The scale factor of 0.5 seemed acceptable so proceeded to look at the failure rates for some devices using that:
![failrate-pml-5-10-lightstaff](https://user-images.githubusercontent.com/55062581/121429714-113ebb80-c92c-11eb-8199-870ac965e07b.png)
![failrate-pml-5-10-towand](https://user-images.githubusercontent.com/55062581/121429755-1a2f8d00-c92c-11eb-88e8-6ec9f9789819.png)
![failrate-pml-5-10-speedstaff](https://user-images.githubusercontent.com/55062581/121429781-21ef3180-c92c-11eb-9009-6bd9ce497f78.png)
![failrate-pml-5-10-mmrod](https://user-images.githubusercontent.com/55062581/121429814-2d425d00-c92c-11eb-9407-90f8f5cdd5fe.png)
![failrate-pml-5-10-speedrod](https://user-images.githubusercontent.com/55062581/121429845-36cbc500-c92c-11eb-8a1e-71eec232ef29.png)

The results for damage wands with the fail rate formula were:
![wanddam-pml-5-10-htw](https://user-images.githubusercontent.com/55062581/121429932-519e3980-c92c-11eb-8186-829f72d70060.png)
![wanddam-pml-5-10-dp](https://user-images.githubusercontent.com/55062581/121429959-582cb100-c92c-11eb-8735-3b7f2d6e486b.png)
![wanddam-pml-5-10-hr](https://user-images.githubusercontent.com/55062581/121429982-61b61900-c92c-11eb-854a-2a133d7b134f.png)
![wanddam-pml-5-10-gm](https://user-images.githubusercontent.com/55062581/121430094-85795f00-c92c-11eb-824f-0b5b28266955.png)

Results for Tangaria's hydra look like:
![failrate-pml-5-10-hydra](https://user-images.githubusercontent.com/55062581/121430235-b35ea380-c92c-11eb-822f-5d2997294c1b.png)
![wanddam-pml-5-10-hyw](https://user-images.githubusercontent.com/55062581/121430383-e143e800-c92c-11eb-9520-4456ac5d0bed.png)

I think the asymmetric form is an interesting idea, but if devices aren't often used for failure rates greater than the transition point (50% failure rate in Pete Mack's post, 38% here because of the asymptotes at 1% and 75%), the part of the curve that's really of interest will be on the right side of the transition where the log() term plays no role.  Making the left side handle more than half of the vertical range (i.e. have the transition occur at say a 15% or 20% failure rate) would be one way of addressing that.

**Comment by backwardsEric** [comment]
As Pete Mack mentioned in http://angband.oook.cz/forum/showpost.php?p=153727&postcount=23 , log() isn't the only choice for the left side of the transition.  These are the results using .75 - .37 / (1 + sqrt(-x)) for x < 0; that will rise more sharply (for the same choice of the tuning parameter p) than log().

Tuning the scaling factor:
![frtune-pms-htw-tow](https://user-images.githubusercontent.com/55062581/121432164-29640a00-c92f-11eb-9a23-68218dbc674e.png)
![frtune-pms-gm-tow](https://user-images.githubusercontent.com/55062581/121432186-31bc4500-c92f-11eb-8448-b84a6e611710.png)

Failure rates with the scale factor set to 0.5:
![failrate-pms-5-10-lightstaff](https://user-images.githubusercontent.com/55062581/121432257-4bf62300-c92f-11eb-99f0-4a25d1141e9f.png)
![failrate-pms-5-10-towand](https://user-images.githubusercontent.com/55062581/121432269-4ef11380-c92f-11eb-8fee-2dbbdcb5cb8c.png)
![failrate-pms-5-10-speedstaff](https://user-images.githubusercontent.com/55062581/121432301-587a7b80-c92f-11eb-8d62-83ec380c2e8a.png)
![failrate-pms-5-10-mmrod](https://user-images.githubusercontent.com/55062581/121432338-629c7a00-c92f-11eb-9669-3d00b11096b0.png)
![failrate-pms-5-10-speedrod](https://user-images.githubusercontent.com/55062581/121432370-6e883c00-c92f-11eb-9751-2d439cc82050.png)

Wand damage:
![wanddam-pms-5-10-htw](https://user-images.githubusercontent.com/55062581/121432483-95467280-c92f-11eb-8a2b-20398c2a8be9.png)
![wanddam-pms-5-10-dp](https://user-images.githubusercontent.com/55062581/121432509-9d9ead80-c92f-11eb-98f8-4ae784c2e595.png)
![wanddam-pms-5-10-hr](https://user-images.githubusercontent.com/55062581/121432551-abecc980-c92f-11eb-980e-2311569c1295.png)
![wanddam-pms-5-10-gm](https://user-images.githubusercontent.com/55062581/121432576-b3ac6e00-c92f-11eb-8890-3abc14e5ccd1.png)

Results for Tangaria's hydra:
![failrate-pms-5-10-hydra](https://user-images.githubusercontent.com/55062581/121432649-cb83f200-c92f-11eb-92ba-39586211178d.png)
![wanddam-pms-5-10-hyw](https://user-images.githubusercontent.com/55062581/121432711-ddfe2b80-c92f-11eb-9e23-75dc5338bc73.png)

Since the right side of the transition is the same as in the previous comment, it's in the portions where the device skill is less than device level that the differences between the sqrt() and log() terms can be seen.

**Comment by backwardsEric** [comment]
There's two things I know of that'll likely have to also be changed if negative device skill levels are possible (i.e. in Tangaria ; I don't know if those are possible in FirstAgeAngband):

1. In the character sheet, the color chosen for the device skill display uses the scaled skill level without an offset as the index into the color table.  Could coerce that index to be in range, but I was leaning towards using a series of tests of device failure rates (use a level 0 device and get more than a 20% failure rate - get the color indicating the poorest skill level, ...) to set the color.  At the high end, would likely have to look at the device damage bonus on a, say level 95 device, since the failure rates won't be too sensitive to the device skill.
2. The penalties and boosts to the device skill in player-calcs.c always scale the device skill (prior to applying the intelligence and class level effects) so a player with a negative device skill can end up having a better chance to use a device when confused/hallucinating/... and a worse chance when blessed.  Could avoid that by  replacing lines like "state->skills[SKILL_DEVICE] = state->skills[SKILL_DEVICE] * 8 / 10;" with "state->skills[SKILL_DEVICE] -= (ABS(state->skills[SKILL_DEVICE]) + 4) / 5;" and "state->skills[SKILL_DEVICE] = state->skills[SKILL_DEVICE] * 105 / 100 by "state->skills[SKILL_DEVICE] += ABS(state->skills[SKILL_DEVICE]) / 20.    I also thought it might be useful to apply a minimum adjustment for those penalties or bonuses so skill levels around zero would still see adjustments when subject to those timed conditions.  So the quoted adjustments would look like "state->skills[SKILL_DEVICE] -= (MAX(20, ABS(state->skills[SKILL_DEVICE])) + 4) / 5;" and state->skills[SKILL_DEVICE] += MAX(20, ABS(state->skills[SKILL_DEVICE])) / 20;".  20 is used there so the heroism/blessing effects will always nudge the skill level, but that means the penalties can pile up more than they used to for a skill level close to zero.

I can work up a patch for the 2nd one pretty easily; the first one I had only started to think about.

**Comment by NickMcConnell** [comment]
I think go with just the second one for now.  For the first, displaying just the raw skill level seems OK to me - the player will end up with an idea form experience of what that actually translates into in terms of failure rates.

**Comment by backwardsEric** [comment]
For the first, I wasn't thinking of changing the display of the raw skill number; it's the color applied to the number that's the issue.

**Comment by NickMcConnell** [comment]
Oh, OK.

**Comment by NickMcConnell** [comment]
I think we can leave that for Tangaria to work out 😄.  The raw skill is bounded below by 10 and above by 150 in FA, so it's not a problem there.

**Comment by backwardsEric** [comment]
Okay.  For the changes in regards to (2), I won't put a minimum on the penalty/bonus amount because that could give a negative skill value (level 1 half-troll warrior with all the possible penalties ended up with a skill of -17 if I used MAX(20, ABS(state->skills[SKILL_DEVICE])) when computing the penalties).
