### ISSUE TITLE
Sound turns off after death

### ISSUE THREAD

**Issue by swim709** [angband/angband#4687]
With sound on, die then start a new game. Sound will not work again until you save, quit, then relaunch the game.

**Comment by backwardsEric** [comment]
With the main.c or main-win.c front ends, there's an assertion failure (line 315 of sound-core.c; "(sound_id >= 0) && (sound_id < next_sound_id)"; next_sound_id is 0) when playing a sound after having died and then starting a new character without exiting the game.  From what I can see, the problem is that sound.prf (pulled in by pref.prf) isn't reloaded by textui_init() if playing again.
