### ISSUE TITLE
Throw and volley are backwards in the roguelike command set

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4777]
The help says that t is throw and v is fire, but they're the other way round in actual play, which doesn't make any sense.

Also, 'f' is a free key, so it could just be throw and fire.

**Comment by backwardsEric** [comment]
Both the in-game documentation, lib/help/commands.txt, and the online version, docs/command.rst , say that 't' is fire and 'v' is throw in the Roguelike commands.  Where did you see the opposite?  As you say, the commands in game are 't' for fire and 'v' for throw.

I haven't seen a description of why those letters were chosen for the commands, but they appear to have been that way since version 3.0.6 (see http://www.thangorodrim.net/help/help_commands.html ) and 2.8.3 (see http://www.phial.com/angdirs/angband-283/lib/help/command.txt ).

Using 'f' for both could be possible but handling ammunition, which can be fired or thrown, would require extra logic or a prompt to determine the player's intent.

**Comment by jl8e** [comment]
Huh. I was sure I read it the other way around in the online help, but I guess I misread.

However, when you've got two actions, one is throw, and it's not 't', that seems backwards. 't' for throw and 'f' for fire would probably be easier for people to remember.

**Comment by NickMcConnell** [comment]
I tend not to change the roguelike commands (apart from adding new ones) where possible because I don't play with them, and I don't want to mess with other people's muscle memory.
