### ISSUE TITLE
(Mac) Clicking on main window causes movement when a different window is in the foreground

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4782]
This may, for all I know, affect Windows and X, but I cannot say.

If you've got a different window in the foreground, whether a different Angband window or a different application, and click on the main window, the game interprets that click as an action.

**Comment by backwardsEric** [comment]
I agree that doesn't match the typical behavior on the Mac, and a change has been submitted so that the first click in Angband's main window when another window was active only changes focus and doesn't do anything else.

Other windowing environments can have different policies for setting the active window (some window managers under X11 have "focus follows mouse" as an option) so what's right for the other Angband front ends does not have to match what is right on the Mac.  The change mentioned above only affects the Mac front end.
