### ISSUE TITLE
Specific drops don't behave as monster.txt says they do

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4808]
In monster.txt, it says: If any drop lines are present, the monster will drop *only* items from its drop lines.

In mon-make.c:mon_create_drop(),  the specified drops are done, then the regular drop code still operates, with the number of items to be dropped unmodified by the specific drop code. The percent chance rolls on the specific drops are also independent of the monster's general drop

Looking at monster memory, this is also a problem with the lore code. A cutpurse "may carry an object or treasure", when it can actually carry both a random object and a scroll of phase door.

**Comment by backwardsEric** [comment]
The way the code behaves seems like the more useful choice:  if the drops due to the flags aren't desired then someone can change flags or flags-off so they don't happen.  Pull request #4831 changes the comment in monster.txt so it matches what the code does and adds rudimentary (just a count, no types) information about specific drops in the monster lore.
