### ISSUE TITLE
Blackguard missing definition for Dark Rituals tome?

### ISSUE THREAD

**Issue by putztzu** [angband/angband#4925]
Hi,
Latest and current stable version of Angband 2.4.
Running on openSUSE 15.3 although I don't think makes a diff.

Problem:
With the Blackguard character, seems that it cannot read the second defined tome/book "Dark Rituals"
I found only one reference to this in the Forums, but I don't think the answerer fully understood the question and provided an incorrect answer at
http://angband.oook.cz/forum/showthread.php?t=9537&page=9

My Investigation and the Probable solution
Did some investigation, it seems that the definition for the "Dark Rituals" tome and its spells are missing completely from class.txt, the following link is to the source
https://github.com/angband/angband/blob/master/lib/gamedata/class.txt

Reading the above file, has the definitions for the first book "Into the Shadows" which is provided by default and the third book/tome "Fear and Torment" 
Based on that info, with the Blackguard character purchased the "Fear and Torment" book and indeed, the book/tome is readable and if at sufficient character level can cast spells from that book/tome.

Additionally, I searched the entire application Github application source and did not find the "Dark Rituals" definitions stored elsewhere.

Recommendation
This suggests to me that this can be solved by simply inserting the required definitions into class.txt.
I assume that whoever conceived of the book has already done the work and experimented with settings.
If it's in someone's private source somewhere or a fork I'm not aware of, I'd expect that this can be resolved simply by pasting that content into class.txt

Else, if no "Dark Rituals" book  should exist, and this is a possibility since the "Fear and Torment" spells seem to be available at levels that are are consistent with progressing from the first book, then the book listing should be removed from a number of .prf files (I don't know what those files are but they contain the text characters "Dark Rituals"

**Comment by backwardsEric** [comment]
The current system is working as intended.  The shadow realm of magic is used by two classes, the blackguard and the necromancer.  The necromancer has a wider range of spells.  Partly to compensate for that flexibility by taking up inventory slots and partly to spread out the gain of power (and thrill of finding it), the necromancer spells are spread over more books, leaving some of them unusable by the blackguard despite being from the shadow realm.

It's possible that the help files or in-game hints need adjustment so players know what to expect from the books when playing a blackguard (or paladin, ranger, and rogue which also don't have access to all the books in their respective realms of magic).  This sort of confusion has come up fairly often for those classes.

To eliminate the unusable books, the existing four realms could be split into eight so that each spell casting class gets its own realm and no unusable books.   However, without any overlap at all in the books, everyone now faces more useless (unless playing with selling on) objects in the dungeon, and some care is likely needed to tweak how often the books that are only found in the dungeon can appear.  Another approach, in line with your first suggestion, is to spread the blackguard's spells over more books so all the books from the shadow realm are usable.  However, without adjusting the power of those spells or coming up with more spells, those spells have become less useful because the character will need to devote an extra inventory slot if the character wants access to all the spells.  For those reasons, and likely others, the reworking of the spells in 4.2 settled on the current system with the hybrid classes (blackguard, paladin, ranger, and rogue) using only some of the books in their respective realms of magic.

**Comment by NickMcConnell** [comment]
Yes, this is indeed the way it is designed to work.
