### ISSUE TITLE
Mac 4.2.3 continually asks to access the documents folder

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4974]
It seems like every time Angband wants to do anything in the Documents folder (program startup, using "open" from the file menu, saving a pref file, etc), I'm getting a security popup that asks whether I want to allow Angband to access my Documents folder

I'm aware this is an OS security thing, but 4.2.2 didn't do this. I assume it asked first time, and that was good. I have changed nothing about where and how I've installed Angband. I just trashed the old app and dropped the new one into my account's Applications folder.

**Comment by backwardsEric** [comment]
Which version of macOS is this?  In the "Security & Privacy" part of the System Preferences, what is shown for the Angband application in the Privacy tab when "Files and Folders" is selected on the lefthand side of the preferences dialog?

With 10.15.7 and trashing a previously installed Angband in /Applications and replacing it with the new version, there was one prompt to access the Documents folder when the game was started, but none since then.  That was using a user account without administrator privileges (authenticated as an administrator to remove the previously installed Angband and replace it with the new one).  That's also what I saw when the application was installed in ~/Applications.

There's a command-line utility, tccutil, to reset what security prompts should be presented.  Does running

```
tccutil reset All org.rephial.angband
```

and then rerunning Angband 4.2.3 only give one prompt to access Documents or is there still several prompts?

**Comment by jl8e** [comment]
11.4
In the files and folders section, it says Angband has access to the Documents folder, but I cannot tell if that's the old copy or not. (I wonder if it matters that I threw the old version away, rather than replacing with the Finder?)

I've reset the security prompts, and it's still doing it.

**Comment by backwardsEric** [comment]
I'll try to set up a virtual machine with Big Sur installed to check this.  Based on what the man page for spctl says, there may be some sort of caching going on (which would go to your question of whether how you removed the old one may have confused it).  So if you haven't already attempted it, logging off and logging back in, or more emphatically, rebooting may be a solution (I don't know if there's some way to use spctl to diagnose what's going on here; tccutil's capabilities are limited).

At least on 10.15 with the different versions of Angband 4.2.* I've run (installed via the dmg or self compiled), there's only one entry for "Angband" in the "Security & Privacy"->Privacy->"Files and Folders" list so I suspect it only keys on the bundle identifier and doesn't distinguish between the different versions.

**Comment by jl8e** [comment]
A reboot did nothing. I manually toggled the setting in the control panel, but that doesn't seem to be helping.

**Comment by backwardsEric** [comment]
With these steps, I never got a confirmation prompt:

1. Install 10.15.7 in a fresh virtual machine.
2. Upgrade that to 11.5.1.
3. Copy Angband 4.2.2 from the dmg file to /Applications.
4. Open Angband, create a new character, enter town, and exit.  Reopen Angband, open the saved character file, and exit.
5. Remove Angband 4.2.2 from /Applications.
6. Copy Angband 4.2.3 from the dmg file to /Applications.
7. Open Angband, open the character saved in step 4, then exit.

I suppose I should have installed and run Angband 4.2.2 when the virtual machine was running 10.15.7 to see if the transfer of the information about the security status, prompts, and perhaps file metadata during the OS upgrade is an issue.

From what I'm seeing in search results is that tccutil is likely the workaround.   Besides the "tccutil reset All org.rephial.angband" which, in principle, should reset all the entries for Angband, perhaps the more specific "tccutil reset SystemPolicyDocumentsFolder org.rephial.angband" is needed?

**Comment by jl8e** [comment]
After that, and an OS upgrade, it's down to once per session at launch.

Does seem likely this is an OS issue, not an Angband one.

**Comment by NickMcConnell** [comment]
I take it this is done now.
