### ISSUE TITLE
Incorrect message for offscreen casting by creatures who can't talk?

### ISSUE THREAD

**Issue by RogueFanUK** [angband/angband#5062]
You get the "something mutters" message when an offscreen monster casts a spell, even for ones who lack the ability to vocalise such as Blink Dogs blinking while off screen, there are probably others.

**Comment by backwardsEric** [comment]
A way to allow more realism for this and for the cases where the visible spell message assumes that the caster has certain physical abilities would be to allow each monster type to override the default spell messages if desired (so something like adding the ability to use "message-vis:<spell_flag>:<alternate_message>" and "message-invis:<spell_flag>:<alternate_message" fields in monster.txt and then check for the presence of an alternative message before using the default one).  Beside blink dogs, magic mushroom patches are something that could benefit from overriding the spell message displayed when not seen.

**Comment by NickMcConnell** [comment]
I think this solution or something like it is a good idea.  Ability to 'personalise' messages is important for immersion.

**Comment by NickMcConnell** [comment]
I think this is done now - anyone disagree?

**Comment by backwardsEric** [comment]
I know some of the spell-casting spiders (abyss spider, ancient spider, spider of Gorgoroth) don't have customized messages.  Should they be like the phase spiders (which do) or Shelob and Ungoliant?  Magic mushroom patches and will o' the wisps also don't have a customized message.  It seems like they should, but it wasn't clear if it should be like what's used for the quylthulgs or something else.

The spell-casting demons, golems, and elementals are other possible candidates for customized messages since at least some of those don't have speech.
