### ISSUE TITLE
Suggestion: have ?a show current keyset commands only, or at least first

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5240]
The =a Options screen's first option (=aa) lets you toggle to using the "Roguelike" keyset. But with that keyset enabled, every time the user wants to consult the keyset command list with ?a, they first have to scroll past the now-useless/confusing "Original" keyset keys.

Theoretically, the game should know that the user was using the roguelike keyset, at which point it could show the roguelike keyset commands first--or better, show ONLY the roguelike keyset commands. And similarly for the Original keyset, have ?a show only the Original keyset commands.

This would make scrolling up and down through the full keyset easier, reduce confusion/overwhelmingness for new players, etc. Showing the user two keysets at once is potentially quite confusing, and it's easy to end up looking at the wrong keyset accidentally; as a new user, when I need to look up a command, the last thing I want is to be shown a list of the WRONG commands. At any rate, as a roguelike keyset user, don't keep making me have to scroll past a list of the wrong commands every time I need to look something up--there is absolutely no need for this.

If the reason for showing both keysets is to make the new player aware that there is an option, the bottom of the command list could simply say something like "An alternate keyset can be selected in Options - User interface options - Option a."

If only the current keyset was shown, the "[x] Keyset Command Summary/====/ /" header could be omitted, allowing more initial display space for commands and further reducing scrolling.

**Comment by backwardsEric** [comment]
Since there isn't much in lib/help/index.txt currently, this could be done with only small changes to the source code and fairly easy-to-maintain changes to the help files.  Load index.txt if using the original keyset and load an alternate version when using the roguelike keyset.  Change index.txt so it links to a version of commands.txt which only has the table for original commands.  The alternate version of index.txt would link to a version of commands.txt which would only list the roguelike keys.

Solving the problem more generally (so it wouldn't be necessary to duplicate help contents; in this case the only duplication is what's in index.txt) would mean building into the help system a way to parse expressions, read from a help file, to get the destinations for links.

**Comment by NickMcConnell** [comment]
I like the first option; the second one looks like over-engineering, especially given the main purpose of the in-game help is the command list now.

**Comment by smbhax** [comment]
> I like the first option; the second one looks like over-engineering, especially given the main purpose of the in-game help is the command list now.

Yeah, I do wish "?" brought up the command list immediately instead of also requiring "a"--I have never found myself wanting to look at symbols with ?b--but I decided to hold my fire on that one. : )

**Comment by NickMcConnell** [comment]
Hm, this has relevance for #5216 as well.

**Comment by NickMcConnell** [comment]
Maybe we actually want to have just a single help file (picked by command set) with the direction to the online help plus the command list.  This would possibly allow removing a bunch of code about the help browsing system (as long as it isn't used for other things such as browsing previous messages).
