### ISSUE TITLE
"hacky keymaps" in /etc/angband/customize/keys-gcu.prf forces sprinting in curses mode

### ISSUE THREAD

**Issue by Zaechus** [angband/angband#5264]
Version 4.2.3

The easy fix is to comment all the lines in `/etc/angband/customize/keys-gcu.prf`, but with this file intact, every arrow key press in curses mode (`-mgcu`) is interpreted as a sprint command. This issue does not affect graphics modes. This issue has persisted for me over multiple Linux distros I've used over the years.

**Comment by NickMcConnell** [comment]
IIRC this was done for the benefit of [angband.live](https://angband.live/)

**Comment by smbhax** [comment]
> IIRC this was done for the benefit of [angband.live](https://angband.live/)

Any idea why? It's just as weird when playing on angband.live as it is locally. Also, it only happens in original keyset mode, not in roguelike mode; when I ran into it, it was really confusing; for a while I thought my keyboard was acting up somehow. Finally I queried keymaps and noticed that no, original keymap arrow keys do ".<number>" instead of ";<number>"; but I found it didn't happen at all in the graphical front end, which was even more confusing.

It seems inconsistent, confusing, unexplained, and a bad idea. New users who want to play using the arrow keys are going to hit this and find the game is almost unplayable.

As well as the workaround @Zaechus mentioned, the user CAN override it manually by overwriting the . keymaps with ; ones in the game's keymap editor--but a new user won't necessarily know that.

**Comment by smbhax** [comment]
Ah, I see: on angband.live, when I replace the . arrow key keymaps with ; ones, then try running by pressing them while holding Shift, the @ does NOT run. I do not have this problem when replacing . with ; in the arrow key keymaps locally in Cygwin.

This looks like breaking things for everyone to work around some sort of angband.live bug.

**Comment by smbhax** [comment]
There was debate on the wisdom of the current implementation at the time, five years ago:

https://github.com/angband/angband/commit/1f296ed865032531aadebe825b24213520bae4d2#commitcomment-22348426

The commit author @OwenGHB even said

> That sounds awful. But feel free to revert, I can just keep patching the builds which end up on my server.

but the commit went through anyway.

Maybe should be reverted.

**Comment by NickMcConnell** [comment]
That "That sounds awful" was referring to the practice of using 1, 3, 5, 7 on the regular keyboard for diagonal directions.  I do think we need a better solution, but I'm not sure what the right one is yet.

**Comment by backwardsEric** [comment]
If angband.live allows configuring a different command line to launch each variant + version, I'd suggest adding an option to main.c (perhaps -p<string> where p is for "preference") that would set a string which could be tested for in the preference files by comparing with the TYPE variable.  Then these preferences that are specific to angband.live could be put in a separate file, keys-live.prf, (keys-gcu.prf wouldn't be needed anymore) and pulled into pref.prf with

```
?:[EQU $TYPE live]
%:keys-live.prf

?:1
```

**Comment by magnate** [comment]
JFTR I have reverted this behaviour in the Debian package of 4.2.5, so that the ncurses port has the same default behaviour as the x11 and SDL2 ports.
