### ISSUE TITLE
Secret doors identified in the look commmand

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#5295]
See [this post](http://angband.oook.cz/forum/showpost.php?p=157444&postcount=1).

**Comment by backwardsEric** [comment]
Were you able to reproduce it?  In Mac version (compiled from the nightly; no optimization and asserts not stripped), I don't see it with secret doors in interesting rooms.  From looking at the code, I also don't see how it is possible unless square_isvisibletrap() is true for the secret door.

**Comment by NickMcConnell** [comment]
No, I didn't even try...

**Comment by smbhax** [comment]
I've never had that happen. The poster did note that it was "in a nightly build from a few months ago (4.2.3-127-gc68e1d5d2)."

**Comment by dburgener** [comment]
I saw this today in a vault.  It was only one granite wall, and when I cast mapping again, it turned into a broken door.  I suspect that this could be caused if the player casts mapping, and at that point it is a secret door.  Then a monster breaks that door, but the player knowledge doesn't update because the player doesn't sees it, but when looking, aux_terrain sees it as FEAT_BROKEN instead of FEAT_SECRET, and therefore views it as interesting?

**Comment by backwardsEric** [comment]
Good catch.  So the two square_isinteresting() calls in target.c and ui-target.c should work with the player's version of the chunk rather than the omniscient view of the chunk.  I'd guess that's also the case for the square_isinteresting() call in player-path.c, though that one should only have a difference between the omniscient view and player's view if the player is running while blind.

**Comment by NickMcConnell** [comment]
Done?

**Comment by backwardsEric** [comment]
Without more details about the original report, it isn't clear if it has the same explanation as dburgener's.  I'd still close this and let any new report get its own issue.

**Comment by NickMcConnell** [comment]
Yep, let's do that.
