### ISSUE TITLE
Identifying a rune that's on multiple items can lead to odd messaging

### ISSUE THREAD

**Issue by jl8e** [angband/angband#5339]
I had two items in my inventory that, unbeknownst to me, had Resist Nexus.

I identified rune on the later one in the inventory, and got the following messages:

You have learned the rune of Resist Nexus
You have the Ring of Dorind <-2, -3> {cursed, ??} (r)
You have 2 scrolls of Identify Rune (i)

It never mentioned the object I read the scroll on, the Cutlass of Langin (t), which I was reading the scroll on. If it matters, this was also the last unknown property on the cutlass.

I assume what happened is that it scanned all the other items to update their info, which changed the current object pointer.

(As a side question, is there a way to dump the message log, so I can cut and paste from it, instead of retyping?)

**Comment by backwardsEric** [comment]
As I understand it, the reason the ring got a message and the cutlass did not was because it was jewelry (due to this part in player_know_object():

```
        if (object_non_curse_runes_known(obj) && tval_is_jewelry(obj)) {
                seen = obj->kind->everseen;
                object_flavor_aware(p, obj);
        }
```

It looks like that is intended to produce a message when a jewelry "flavor" is recognized for the first time.  If that's the intent, should add a "&& ! obj->artifact" to the test so there's no message when an artifact necklace or ring has all its non-curse runes identified.
