### ISSUE TITLE
Equippable comparison could be more informative

### ISSUE THREAD

**Issue by jl8e** [angband/angband#5348]
In the item listing, there's the object symbol, a mystery letter (seems to be one of e, h, or occasionally p or f), then its name.

First of all, AFAIK, the mystery letter is explained nowhere. I can deduce what it means, I think. (Equipped, home, carried, and on the floor). 'i' would be a better choice for carried than 'p'.

Secondly, and this is mostly about elvenkind items, which are both armor and shields: I can't tell which is which from the object symbol. I've been playing this game since forever, and still can't tell you which of the various parentheses and brackets are armor and which are shields. Much more useful would be the inventory slot they use. (Yes, they're sorted by slot; the boundaries are not always obvious.)

(Also, until I wrote this, I didn't even realize they were sorted by slot.)

**Comment by jl8e** [comment]
And, while I'm at it, the headers have two light-colored in a row (disenchant and fear), but the columns below keep alternating between light and dark, so headers become the opposite color from their column at that point

**Comment by backwardsEric** [comment]
As you guessed, the mystery letter signals the location of the item.  'e' is equipped, 'p' is pack, 'f' is floor, 'h' is home, and 's' is a store other than home.  The item attributes have the same ordering as on the resistance part of the character sheet (but are presented from left to right rather than from top to bottom in three columns) so "Bl" is the blessed melee flag and "IH" is the impaired hit point recovery curse.

**Comment by NickMcConnell** [comment]
Is there anything left to do here?

**Comment by NickMcConnell** [comment]
Closing this as done.
