### ISSUE TITLE
Issues with generate_cave()

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#5490]
I see two possible problems here:

1. The builder can return false (caverns, for example), which means the "Failed to find builder" error is a bit misleading;
2. More seriously, if a builder returns false or there is a failure because of too many monsters, any artifacts created in the generation attempt retain their "created" status, so will silently fail to generate for the rest of the game.

Happy to be proved wrong.

**Comment by backwardsEric** [comment]
(1) is definitely an issue as failing to find a builder is explicitly trapped in choose_profile() and causes the application to quit.  The question that remains is whether to have a mechanism for the builder to get a more informative message back to cave_generate(), have the builder issue the message itself, or to use a different generic error message in cave_generate().

For (2), most of the builders explicitly add objects at the point where they'll always successfully return so any lost artifacts would have to be placed by room generation for the level.  Can avoid those losses by moving the artifact preservation logic in prepare_next_level() to its own function and call that before calling cave_free() when returning due to an error from a level builder (can't incorporate that logic into cave_free() because that is also used to free up chunks after they've been copied and, for that, wouldn't want the special handling of the artifacts).

**Comment by NickMcConnell** [comment]
Yes, I have just used that moving of the artifact preservation logic in the Sil rewrite.  I'll port the method to Angband at some point.  Probably best to wait either for me to do that, or for me to get the Sil rewrite code public, as my (optimistic) aim is to try and keep the two codebases to share code as much as possible.

**Comment by NickMcConnell** [comment]
Thanks for the sanity check 😄
