### ISSUE TITLE
MSYS2: Accented letters display incorrectly

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5498]
MSYS2-compiled latest Angband source running SDL2 and GCU front end in Windows 11 Home. Used the sound-support makefile https://github.com/backwardsEric/angband/blob/msys2-sdl2-sound/src/Makefile.msys2.sdl2

I've come across three instances of accented characters so far while running MSYS2-compiled Angband's SDL2 front end, and they have displayed incorrectly, showing as corrupted characters in the recall subwindow (9x15x.fon), and monster list subwindow (8x12x.fon), and as blank characters in the main window's recall display (16x16x.fon).

![01_nar](https://user-images.githubusercontent.com/91744319/196016915-2abfecbc-2df2-4d0c-ac67-c12a5d58ced9.jpg)
![02_dunadan](https://user-images.githubusercontent.com/91744319/196016917-b7b46e23-05df-4390-9ab1-81a31ef76b65.jpg)

Video: https://youtu.be/HoSvVNSILf4?t=5070

From lib/gamedata/monster.txt, the incorrectly displayed lines appear to have been:

name:dúnadan of Angmar
name:Nár, the Dwarf
desc:The friend and companion of the dwarven king Thrór,

I noticed other instances of garbled names among the Uniques in my ~ knowledge base.

![03_uniques](https://user-images.githubusercontent.com/91744319/196016920-5e890a4d-6809-4a53-a54a-d65cdbec0dbc.jpg)

The accented characters also display incorrectly in the MSYS2-compiled GCU front end, running through Windows' CMD terminal.

![04_gcu](https://user-images.githubusercontent.com/91744319/196016932-29967561-a647-4509-9767-ffd37bc5d253.jpg)

In contrast, the accented characters display correctly in the knowledge base of the other graphical versions of Angband that I checked: the latest standard Windows version from rephial.org, and the SDL2 front ends I compiled and ran myself from the latest source code under WSL Ubuntu and Cygwin/X.

As far as I can tell from the MSYS2 site ( https://packages.msys2.org/package/mingw-w64-x86_64-ncurses ), cursesw is included in the mingw_w64_x86_64-ncurses package, which I installed in MSYS2 prior to compiling.

I installed the mingw-w64-x86_64-utf8cpp and mingw-w64-x86_64-libutf8proc packages and recompiled, but this did not fix the problem.

-----

In 2011 there was discussion of issues sounding similar to this: a Mac-specific issue was marked as fixed, and a remaining problem was supposedly going to be resolved by a then-impending move from Latin-1 to UTF-8 encoding:

- https://github.com/angband/angband/issues/3494 (closed as duplicate of old stuff; says from 2011 comment by myshkin "the sdl portion is a more general problem that noz will address with the utf-8 code")
- http://angband.oook.cz/forum/showthread.php?p=53225#post53225 Continuing the discussion in 2011, myshkin added "The original issue that fph reported is not actually specific to the SDL port. noz is working on moving our codebase from the Latin-1 encoding to UTF-8; the inconsistent display of accents should go away as a side effect of this change."

**Comment by backwardsEric** [comment]
Which environment are you using under MSYS2?  According to https://www.msys2.org/docs/environments/ , some environments use MSVCRT as the C runtime and that does not support UTF-8 locales.  That limitation isn't listed for the other C runtime, UCRT, that's used by other environments.  Potentially also relevant is this, https://stackoverflow.com/questions/28481410/how-to-set-console-encoding-in-msys (though from the title it's for MSYS rather than MSYS2), about setting the language and character set for the shell.

**Comment by smbhax** [comment]
Thanks! I set the character set option to UTF-8 as given in that second link, just in case. : )

I've been using MinGW64, it's the one mentioned in the Angband manual's build instructions: https://angband.readthedocs.io/en/latest/hacking/compiling.html#using-msys2-with-mingw64 . I tried MSYS, UCRT64 and CLANG64, but they all produce an immediate series of error messages, and the build aborts:

$ make -Bf Makefile.msys2.sdl2
make: sdl2-config: No such file or directory
make: sdl2-config: No such file or directory
make: sdl2-config: No such file or directory
make: sdl2-config: No such file or directory
        CC main.c
make: gcc: No such file or directory
make: *** [Makefile.msys2.sdl2:140: main.o] Error 127

**Comment by backwardsEric** [comment]
I suspect this will result in a bunch of errors about libraries that can not be found or still have problems displaying the accented characters, but what happens if you compile and link Angband in the MINGW64 environment and run the executable in the UCRT64 environment?

To verify what locale is being used, what does running ```env | grep LANG``` report?  Also, what does running ```nm -u src/main.o | grep -i setlocale``` report when run from the top-level of Angband?  That's to verify that the locale check in main.c is being compiled into the executable.

main-sdl2.c assumes wide characters are using a Unicode encoding (UTF32 in the native byte order where each glyph can be cast to a unsigned 16 bit int or UTF16 in the native byte order where no glyph requires a surrogate pair); my hypothesis is that mbstowcs() in the MINGW64 environment breaks that assumption, regardless of which locale is used.  Given that there's no prebuilt SDL2 packages for the UCRT64 environment, the solution is likely to change the source code to override the UTF8 to wide character conversion when compiled in the MSYS2 environment.  Something similar may be appropriate for the GCU front-end, but I haven't looked at ncurses to know how it's handling wide characters.

**Comment by smbhax** [comment]
> what happens if you compile and link Angband in the MINGW64 environment and run the executable in the UCRT64 environment?

The game runs normally in its own screen. The accented characters are still scrambled.

> To verify what locale is being used, what does running `env | grep LANG` report?

smbhax@DESKTOP-64GQN1N MINGW64 ~
$ env | grep LANG
LANG=C.UTF-8

smbhax@DESKTOP-64GQN1N UCRT64 ~
$ env | grep LANG
LANG=C.UTF-8

smbhax@DESKTOP-64GQN1N MSYS ~
$ env | grep LANG
LANG=C.UTF-8

smbhax@DESKTOP-64GQN1N CLANG64 ~
$ env | grep LANG
MSYSTEM=CLANG64
LANG=C.UTF-8

> Also, what does running `nm -u src/main.o | grep -i setlocale` report when run from the top-level of Angband?

I'm not sure how to do this.

**Comment by smbhax** [comment]
> Also, what does running `nm -u src/main.o | grep -i setlocale` report when run from the top-level of Angband?

smbhax@DESKTOP-64GQN1N MINGW64 ~/angband
$ nm -u src/main.o | grep -i setlocale

smbhax@DESKTOP-64GQN1N UCRT64 ~/angband
$ nm -u src/main.o | grep -i setlocale

smbhax@DESKTOP-64GQN1N MSYS ~/angband
$ nm -u src/main.o | grep -i setlocale

smbhax@DESKTOP-64GQN1N CLANG64 ~/angband
$ nm -u src/main.o | grep -i setlocale

The last, clang, one, prompted my antivirus to scan nm.exe the first time. None of them resulted in any output.

**Comment by backwardsEric** [comment]
Thanks for that information.  That should give me enough to experiment with what mbstowcs() does in MSYS2 on GitHub's Windows runners.

**Comment by smbhax** [comment]
Yes! That's fixed it as far as I can see. : ) All the accented characters in my lore.txt display correctly in both the SDL2 and GCU front ends when I build under MSYS2 MinGW x64 with those file changes.

**Comment by smbhax** [comment]
(Uninstalled those two utf8 packages I'd installed earlier and confirmed they had nothing to do with the fix. And it still seems okay when I leave Locale set to "Default" (with no Character Set specified) in the MSYS2 terminal's Options dialog.)
