### ISSUE TITLE
unit tests require game to be installed at $PREFIX

### ISSUE THREAD

**Issue by elly** [angband/angband#5517]
The unit tests often call into init_angband(), which tries to load game data out of $PREFIX and dies if it's not there. They probably need to either use the source root as the game data dir while running, or stop calling init_angband().

**Comment by backwardsEric** [comment]
For the case where the game is to be installed elsewhere (i.e. not a --with-no-install configuration) is the intent to be able to run the tests cases before installation is done, after the installation is done (using the installed game data files), or both?

The current configuration does allow the tests to be run in the --with-no-install case or after installation (though if it's a setgid installation, the test cases which try to read or write a save file will fail because the extra step to make the test case executables setgid has not been done).  If the tests are to be run only before installation, then, like you say, test-utils.c's set_file_paths() could be modified to use the source directory's lib folder.  Being able to run the unit test cases before or after installation would require additional information from the person running the tests about which set of game data files to use (to make that simple for that person, could have separate rules in the makefiles for running the test pre- or post-installation; they'd pass different options to run-tests which would then pass along the directory to use to the individual unit test case executables).

**Comment by elly** [comment]
@backwardsEric I want to be able to run the tests using the in-tree data files before installation - ideally as part of a CI pipeline which does a build-check-install in a hermetic environment.

Something like this: https://github.com/angband/angband/pull/5518

**Comment by backwardsEric** [comment]
Resolved by https://github.com/angband/angband/pull/5944 .  However, the path to the data files for the unit tests is a relative one.  So one has to be careful about the working directory if directly running run-tests or one of the unit test cases: use the top-level directory for the source tree as the working directory.  Running the test cases via the build system will handle setting the working directory.
