### ISSUE TITLE
Should we kill main-ibm.c?

### ISSUE THREAD

**Issue by elly** [angband/angband#5531]
It was originally removed by takkaria in the 3.0.7 era, then re-added in 950790c6065ff2a5a82bd79050f8f5fbb99f1d13 earlier this year with no obvious rationale (see #5381). There are a couple of problems with it:

1. It is not covered by CI
2. It very likely does not build, since it uses the pre-stdint types that we removed
3. It is the only platform where wide chars are not supported, which requires text_wcschr_hook, text_wcslen_hook, and friends to exist when we could otherwise remove them

I propose removing main-ibm.c and Makefile.ibm again, for good this time :)

**Comment by backwardsEric** [comment]
As an alternative, https://github.com/angband/angband/pull/5536 , addresses #1 and #2 . #3 may be less of an issue when and if https://github.com/angband/angband/issues/5499 is resolved. I can't speak for the rationale for main-ibm.c but imagine that it could be that building ncurses and then using main-gcu.c in that environment is impossible or too painful.

**Comment by NickMcConnell** [comment]
My reason for allowing it in is that Angband is a community game, and someone in the player community wanted this enough to do the work to get it ready.  The presence of the NDS/3DS ports is similar - they're all a bit niche, but then so are we.  And it isn't too heavy a burden for the rest of the codebase (unlike the borg, removed on my watch, for example).

**Comment by smbhax** [comment]
I would accept being able to load DOS font characters into the SDL2 front end, say by loading lib/customize/font-ibm.prf -- currently, that just scrambles the characters in that front end, not surprisingly. ^ _^

DOS is just about my favorite front end for Angband, there's something about those extended ASCII checkerboard DOS blocks for tunnel walls that just works really well visually, along with the big chunky text, small window, etc. I might be running this as my preferred way to play the game, except that it runs pretty slow for me in DOSBox. Still, it's really cool I could even get current Angband compiled for DOS and running in DOSBox at all. : D

I did run into a couple hiccups trying to get it going which I THINK might be issues with the Angband manual compilation instructions and/or Makefile.ibm; I don't know if this is the best place to roll those out but here goes anyway:

- I was using Cygwin

The Angband compilation instructions say to do

DJGPP_PREFIX=$HOME/local/cross-djgpp

before ./build-djgpp.sh. This doesn't work for me: make just goes ahead and builds in the default directory from script\10.3.0 (DJGPP_PREFIX=${DJGPP_PREFIX-/usr/local/djgpp}) instead.

Likewise, the Angband manual compilation instruction

PATH=$PATH:$HOME/local/cross-djgpp/bin

resulted in a failed make. I don't think it worked when I put the correct, default path in there, either. I ended up navigating to /usr/local/djgpp and doing

source setenv

there. Then make worked.

Then

make -f Makefile.ibm dist

had three problematic lines:

Line 104

	@cd $(TMPDIR)/lib/gamedata ; for i in *.txt ; do iconv -f UTF-8 -t CP437//TRANSLIT $$i -o $$i.new ; mv $$i.new $$i ; done

was producing iconv: -o errors. I don't know what that -o is supposed to be, but it isn't a valid iconv parameter. I ended up having to chop that and the following mv out; this shortened version

	@cd $(TMPDIR)/lib/gamedata ; for i in *.txt ; do iconv -f UTF-8 -t CP437//TRANSLIT $$i ; done

worked, or has seemed to so far--I mean, the game seems to run okay.

Line 126

	@iconv -f UTF-8 -t CP437//TRANSLIT -o $(TMPDIR)/changes.txt ../changes.txt

Again, the -o part wasn't parsing. This shortened version appears to have worked:

	@iconv -f UTF-8 -t CP437//TRANSLIT $(TMPDIR)/changes.txt

Except, it needed a new line inserted before that:

	@cp ../changes.txt $(TMPDIR)

Line 128

	@cp $(EXE) $(TMPDIR)

did not work, I guess because the install part of the Makefile had already moved the compiled angband.exe into the parent directory. I had to go with

	@cp ../$(EXE) $(TMPDIR)

instead.

**Comment by backwardsEric** [comment]
For emulating code page 437 in the SDL 2 front end, if you have access to a fixed-width TTF font with Unicode indexing that has support for the additional symbols (the "Font Coverage" section of https://en.wikipedia.org/wiki/Block_Elements may have some leads for such fonts), you could copy or link that font file to Angband's lib/fonts and use the table at https://en.wikipedia.org/wiki/Code_page_437 to generate a preference file from font-ibm.prf that would give the DOS client's appearance with that font.

As for the DOS instructions, the ones in compiling.rst do mention that it was done on a Linux host.  Probably we should modify Makefile.dos to mention that it has Linux-specific parts (the iconv issue you encountered is one; I know the instructions also didn't work for me on MacOS).

**Comment by smbhax** [comment]
I've just been finding I can get an "old school" .otf DOS font, put it in the Angband fonts directory, select it in the SDL2 front end, and then loading font-ibm.prf DOES work! It's just that the fonts are all too small, Angband > Font > Size doesn't do anything; can't find a way to scale them up. Hm so close!

If I put a .ttf in there, I can select it, and the size setting does work, although the scale of the window itself gets a little tricky to manage. And since these tend to be designed for size 8, I can scale to 16, but the scale stops at 23, so 16 is the largest non-blurry size I can use. That would be just about okay, though.

But the ttf fonts I have aren't giving the DOS-specific characters when I load font-ibm.prf (they and the otfs are from https://int10h.org/oldschool-pc-fonts/download/ ); I'm not sure if they don't have them, or what I would need to change the values in font-ibm.prf to to access them, if they do. The .otf format fonts work without any adjustment of font-ibm.prf, they're just a bit small.

**Comment by smbhax** [comment]
Sorry, it was .fon format that works with no changes, just the size is tiny. I'm gonna hunt around and see if there are any that are a little larger.

I think the .ttf fonts are just not going to work--I can't find any with the DOS-specific characters, and also they come out slightly blurry, even if you set the terminal's font size to match their original size.

About the Angband manual DOS compilation instructions, they say "These instructions were written using a Slackware64-15.0 host." Is that the tip-off that they're for Linux? I have no idea what Slackware is--if it's Linux, I'm not on Linux, so, that doesn't help tell me it's Linux; in any case, it doesn't say that they're only for Linux. I thought Cygwin might be okay because the docs for https://github.com/andrewwutw/build-djgpp say it supports Cygwin--and that part of it definitely worked fine.

But, turns out they do work in Cygwin, just with a little massaging! : D

I was coming back to report something that could possibly be Cygwin-specific with them, though: after I'd been compiling the DOS port, when I tried to compile the GCU front-end, even after having reverted all the files that "git status" was showing me had been changed after running Makefile.ibm, and doing "make clean," I was getting a UTF-8 error compiling main.c. Freaky. Must have been something I was missing somewhere. I had to blow away my angband directory and clone the project from scratch before I could compile the GCU Angband again.

**Comment by smbhax** [comment]
Found a .ttf font with the DOS characters: https://www.dafont.com/perfect-dos-vga-437.font

Comes up with the right symbols on loading the default font-ibm.prf.

Only very slightly blurry in Cygwin GCU; perfectly sharp at size 32 in MSYS2 SDL2, and that's just about the right size, too. Only slightly quirk is small gaps between the checkerboard tiles. But this one is probably close enough that I could let the IBM port go. ^_ ^

![Untitled-1 copy](https://user-images.githubusercontent.com/91744319/207994875-575ad33b-eaaf-4689-949e-ce3aa12a62a1.jpg)

**Comment by backwardsEric** [comment]
As you found, a font with code page 437 indexing would work with font-ibm.prf.  For a font with Unicode indexing, I was recommending replacing the values in font-ibm.prf with the closest match from Unicode (that link to Wikipedia's description of code page 437 has a table of those).  For instance, that would mean changing "feat:open floor:*:1:250" to "feat:open floor:*:1:0xb7" and "feat:granite wall:*:1:177" to "feat:granite wall:*:1:0x2592".

**Comment by NickMcConnell** [comment]
I think the answer is no, and any other issues can be raised as ... other issues.
