### ISSUE TITLE
Running player loses a turn on reaching a known trap

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#5544]
In `move_player()`,
 `	} else if (trap && player->upkeep->running && !trapsafe) {
		/* Stop running before known traps */
		disturb(player);
`
simply aborts running, but energy to move the player has already been expended in run_step().  If I'm right, there should be a line
`player->upkeep->energy_use = 0;`
after the disturb.

**Comment by backwardsEric** [comment]
In my testing, the test for visible traps in run_test() appears to prevent that code in move_player() from coming into play (I haven't verified that it is completely dead code; i.e. if move_player() can be called elsewhere when player->upkeep->running is true).  The other cases where move_player() does nothing while running (trap detection status change at line 1089 and bailing out from running into lava at line 1106) do occur and cause the player to expend energy.  I'd ```add player->upkeep->energy_use = 0;``` for all 3.

In the walking case, there'll be energy spent if the player chooses to not walk into lava (i.e. line 1110 causes step to be false) because do_cmd_walk() sets energy_use before calling move_player().  Should it cost energy?  If the player tries to walk into unknown but impassable terrain (i.e take off light source and walk into an unexplored square with a wall), that takes energy as well; should it?

**Comment by backwardsEric** [comment]
#5558 adds rebates for the three cases that could be triggered by running and also for the case where walking into lava is rejected by the confirmation prompt.  It does not rebate walking into impassable terrain (that's to uphold do_cmd_walk()'s promise that confused moves always take energy).

In that vein, should there be a confirmation prompt for walking into lava if the player is confused?  If the prompt remains in the confused case, then #5558 would have to be altered so there's no rebate when the confirmation blocks the move and the player is confused.
