### ISSUE TITLE
"The baleful presence of $the silent watcher inspires your enemies."

### ISSUE THREAD

**Issue by jdholbrook81** [angband/angband#5845]
There is a $ in the above line when I run into silent watchers. Seems to be coming from this line, but not sure what is replacing {name}.

https://github.com/angband/angband/blob/b56d65abeb85337e32489bb248ee2beb9623ace0/lib/gamedata/monster.txt#L8521

**Comment by backwardsEric** [comment]
The version of monster.txt included in 4.2.5 had a '$' before "{name}" leading to the '$' in the message seen on screen.  That's been fixed in the post 4.2.5 builds since 4.2.5-16-g2e4e7bbff .  {name} is replaced with the name of the creature casting the spell.  The {} expressions that are expanded are described in the comments at the start of monster_spell.txt.
