### ISSUE TITLE
Configure improvements

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#5989]
Submitted by the Invisible Stalker (for FA2.0.1, but applies to V I think):
This is pretty minor but the --help option on configure is giving
incorrect information about the default value of bindir. The problem
is that configure.ac changes the default from $PREFIX/bin to
$PREFIX/games but autoconf doesn't change the boilerplate part of
the ./configure --help text to reflect this.

Even more minor, I think "x$wsetgid" = "xyes" would be a bit more
portable than "x$wsetgid" == "xyes".

**Comment by backwardsEric** [comment]
The second part should be already be done by https://github.com/angband/angband/pull/5949 in Vanilla and FAangband (grep '==' configure.ac in the current heads for both reports nothing).

The first part can not be handled cleanly by Angband (likely because overriding bindir is contrary to the GNU standards layed out in https://www.gnu.org/prep/standards/html_node/Directory-Variables.html ).  At least in autoconf 2.69, that help text is fixed in autoconf_installation_prefix/share/autoconf.m4f so would need a change in autoconf or add a hack in autogen.sh to edit the generated configure script (but that would not help if the end user runs autoconf directly rather than using autogen.sh).

**Comment by NickMcConnell** [comment]
OK, calling this as done as it can be.
