### ISSUE TITLE
Borg and Restricted Stairs

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6034]
@agoodman00 

I acknowledge that this is the lowest priority possible bug but...

If the "restrict upstairs" birth option is on, the borg will simply stand on the upstairs trying fruitlessly.  Eventually, this should be handled somehow.

**Comment by agoodman00** [comment]
Hmmm. Is that a birth option?  I think for now I will probably have to add an edit to just not allow the Borg to run if that option is on.  There’s just too many places the code tries to go upstairs to make it work well with that option on.  Eventually it can get recoded to do something more reasonable. It’s needs a complete replan to make sure it always fully explores levels and never tries to escape using WoR.

**Comment by Netbrian** [comment]
Yeah, it's a birth option.

I wasn't expecting the borg to handle ironman mode well, I just wanted to see what would happen.  (I think the borg is more entertaining at lower dlevels)

The borg does seem to deal OK with restricted Recall though.

**Comment by agoodman00** [comment]
> The borg does seem to deal OK with restricted Recall though.

My guess, without looking at the code, is that he handles this because the game doesn’t give him scrolls.  Eventually he will not go deeper because he will think “I need x WoR ability to go deeper than..”
I also guess that if you used wizard mode to give him an artifact with a WoR activation he would keep trying to use it.

**Comment by Netbrian** [comment]
Fix validated!
