### ISSUE TITLE
Borg Unwilling to Dig

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6040]
[Cirialf 20240913.zip](https://github.com/user-attachments/files/16996132/Cirialf.20240913.zip)

@agoodman00 

In this case, the borg is stuck.  For whatever reason, it doesn't seem to realize it could just dig itself out.

**Comment by agoodman00** [comment]
Ya, the borg was coded to only dig his way out if he could dig quartz or better.  This is because it isn't a good idea for him to go around digging items/money up unless he is a good digger. Since this guy couldn't get the quartz he gave up and didn't dig the magma.  I added https://github.com/angband/angband/pull/6042 to allow him to be more liberal in his digging when he is twitchy (has nothing he knows to do so is just moving randomly).

**Comment by agoodman00** [comment]
FYI @Netbrian I am leaving the issues for you to close if you feel the change fulfills the issue.  All the issues should have code checked in and in the latest nightly now.

**Comment by Netbrian** [comment]
Looks good, closing!
