### ISSUE TITLE
SDL2: Toggling Window 0 off abruptly closes the game

### ISSUE THREAD

**Issue by smbhax** [angband/angband#6058]
MSYS2-compiled SDL2 front end, latest code, Windows 11

1) Run angband.exe
2) Select the "Menu - Window - Window 0" menu toggle

== Angband abruptly closes.

Upon restart, progress does appear to have been saved, at least (if you had gone through character select and moved your @, for instance), although there was no notification.

**Comment by backwardsEric** [comment]
That is the expected behavior.  If you were running in windowed mode, toggling off a window in the menus is equivalent to using the control on the window's frame to close the window.  For window 0, that saves the game and closes the application without prompting the user.

Since a stray click (or key press) is more likely in the menus than on the window's frame, perhaps a confirmation dialog would be appropriate for the window 0 entry in the menus.

**Comment by smbhax** [comment]
Yeah I think it needs something. Although personally, I don't think closing the game that way should be allowed: it's too confusing, and it duplicates other functionality.

Incidentally, the white square indicator for the toggle state is not very intuitive--it doesn't say "this is a toggle, toggled on" to me; actually, it looks more like a checkbox that is currently toggled OFF (although that would more obviously be an empty box rather than a filled box; and a toggle toggled on would usually be a box with a check mark in the middle).
