### ISSUE TITLE
Borg Potion Struggle

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6068]
The borg still seems to be struggling with potions.  He has them in his inventory, but can't seem to acknowledge it.
[20240925 Cirialf.zip](https://github.com/user-attachments/files/17152809/20240925.Cirialf.zip)

@agoodman00

**Comment by agoodman00** [comment]
From what I can see, this borg wants 30 *HEAL* between home and inventory and he has 15.  Probably used up what he had going after "extra" uniques.  He wants there to be less than three alive before he attempts to kill Sauron since Morgoth will summon uniques.  So, once he has all the potions he needs he will stick around 98 till he kills all but 3 uniques.  
If I ^aczl 15 times (to give him his 30 *healing*) he complains that the Mouth of Sauron is still alive.
I did notice a bug here that if I do ^z2 it complains about staffs but if I do ^zx1 (step once) then ^z2 it gives the more correct "scumming *heal* need  15" (something like that).  So... gotta work on that one.

**Comment by Netbrian** [comment]
Can you look into tweaking this rule to count potions of Life when getting to 30?

Also, this borg seems to report not having enough food even when he can cast satisfy hunger.

**Comment by agoodman00** [comment]
Hmm, I think for a while "amt ezheal" was \*healing\* + life but it looks like at some point they were broken apart into two different traits... I am not sure I can just combine them again.  Probably there was a reason to separate them.  I am guessing it messed up collection.  I will look at just adding amt life to the 30 formula and probably a couple of other places where just ezheal is checked.  I think borg.txt and the code will need to change.

**Comment by agoodman00** [comment]
checked in   https://github.com/angband/angband/pull/6071

**Comment by NickMcConnell** [comment]
Fixed in 975b292c
