### ISSUE TITLE
Borg Struggles When Told to Kill Uniques

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6080]
[Cirialf Unique.zip](https://github.com/user-attachments/files/17260741/Cirialf.Unique.zip)

The borg does not seem to be have correctly when borg_kills_uniques is enabled.  This borg says his target depth is 6, to kill Mughash.  However, he seems to be unwilling to dive that far, and instead spends all his time on dlevels 1-3.

@agoodman00

**Comment by Netbrian** [comment]
In other cases, he dives down to dlvl 17 or so, still without having killed Mughash.  It's all very strange.

**Comment by agoodman00** [comment]
I will check into this but the "kill uniques" is "make sure no more than 3 uniques are alive at or above my depth".  So he could be good to go to 17 if the live uniques are Mughash, Ulfast and Nar.  He will then report that Mughash is holding him back.

**Comment by agoodman00** [comment]
hmmm, looks like the unique check is not correct.  it is keeping track of the depth of the most shallow unique but really it should keep track of the depth of the third most shallow living unique.   I am going to have to poke at what this is doing but it seems wrong to me.

**Comment by agoodman00** [comment]
I added https://github.com/angband/angband/pull/6082 which should make the unique check more accurate and better documented in the message about why he isn't going deeper.

**Comment by agoodman00** [comment]
btw, @Netbrian I think the code for all of the borg issues is in the nightly at this point.  Do you want me to add a comment when that is so?  
Also I am leaving closing the issues to you since you will be in the best position to say if the fix I did solves what you think it should solve.  Not that I am against leaving issues open and saying on them "I wrote up A, you fixed X, which helped but we also need Y".
