### ISSUE TITLE
Borg Priest Struggling

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6097]
I've noticed that the borg sometimes struggles to target monsters and then disconnects.  I've attached examples!

@agoodman00 

[Cirialf Priest.zip](https://github.com/user-attachments/files/17386230/Cirialf.Priest.zip)

**Comment by agoodman00** [comment]
Looks like this is the "induce sleep in a single monster" activation.  I am guessing the borg thinks this is an area of effect.

**Comment by agoodman00** [comment]
yup.  easy fix https://github.com/angband/angband/pull/6098

**Comment by Netbrian** [comment]
Would it be possible for the borg to just check the code somehow to determine what is or is not a bolt?  I'm surprised it's hard coded.

**Comment by agoodman00** [comment]
> Would it be possible for the borg to just check the code somehow to determine what is or is not a bolt?  I'm surprised it's hard coded.

Probably.  As I recall there was a lot of things, like damage and area of impact, that it's possible to pull out of the data stored in the game code.  There are two problems 
1) since spell can have multiple effects or selected effects (like dragon breath potions) the way it is stored is complex. The borg could read the gamedata file itself but that would take a bunch of code. 
2) philosophically the borg shouldn't be accessing game internals. Since the borg is testing the game it should be able to be stand alone and just feed the game keypresses. This is violated in several places but it is the philosophy of the code.

**Comment by Netbrian** [comment]
Ok, that makes sense!  Well, I'll keep looking!

**Comment by Netbrian** [comment]
This has been validated!
