### ISSUE TITLE
Borg Problems With Staffing

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6102]
This borg won't dive because he doesn't have teleport staves.  However, he has them in his house -- he just won't go and get them.

[PLAYER.zip](https://github.com/user-attachments/files/17411754/PLAYER.zip)

**Comment by Netbrian** [comment]
@agoodman00

**Comment by Netbrian** [comment]
On the other hand, this borg has twenty staves of teleportation, with one charge total.  Not sure what's going on here.

[Cirialf Staff.zip](https://github.com/user-attachments/files/17414761/Cirialf.Staff.zip)

**Comment by agoodman00** [comment]
> This borg won't dive because he doesn't have teleport staves. However, he has them in his house -- he just won't go and get them.
> 
> [PLAYER.zip](https://github.com/user-attachments/files/17411754/PLAYER.zip)

I think you attached the wrong save.  This one is a clevel 1 ranger.

If the issue is "he is in the dungeon and he won't go back to get his staves from home"... he should, eventually.  The borg doesn't know his problems will be solved by going home.  There is no check for that.  The next time he DOES go home, he should pick up the items he needs to be most powerful and there is a bonus for how deep he can go.  As a result, as long as he has room and isn't making himself weaker in other ways, he should eventually go up and grab the staffs.

**Comment by agoodman00** [comment]
> On the other hand, this borg has twenty staves of teleportation, with one charge total. Not sure what's going on here.
> 
> [Cirialf Staff.zip](https://github.com/user-attachments/files/17414761/Cirialf.Staff.zip)

There is code to 
"        /* Crush Stacked Wands and Staves that are empty.
         * ie. 5 Staffs of Teleportation (2 charges).
         * Only 2 charges in 5 staves means top 3 are empty.
         */
"
but it doesn't seem to be working.  It should just be assuming you are crushing one but instead it is assuming you crush all.  Let me look into this.

**Comment by agoodman00** [comment]
created https://github.com/angband/angband/pull/6104 but it is worth noting it won't IMMEDIATELY fix Cirialf Staff.zip.  The problem is Crialf got himself into a position where getting rid of one staff won't help his weight situation so dropping one won't increase his power.  He will drop staves as he finds other things to carry that he wants to hold onto more.,, or you could destroy 15 staffs and he shouldn't get in this situation again.

**Comment by Netbrian** [comment]
> > This borg won't dive because he doesn't have teleport staves. However, he has them in his house -- he just won't go and get them.
> > [PLAYER.zip](https://github.com/user-attachments/files/17411754/PLAYER.zip)
> 
> I think you attached the wrong save. This one is a clevel 1 ranger.
> 
> If the issue is "he is in the dungeon and he won't go back to get his staves from home"... he should, eventually. The borg doesn't know his problems will be solved by going home. There is no check for that. The next time he DOES go home, he should pick up the items he needs to be most powerful and there is a bonus for how deep he can go. As a result, as long as he has room and isn't making himself weaker in other ways, he should eventually go up and grab the staffs.

This is a better save.  It's not a matter of "not knowing he has teleport at home", it's a matter of not getting the teleport he has at home once he's in town.

[PLAYER.zip](https://github.com/user-attachments/files/17435233/PLAYER.zip)

**Comment by agoodman00** [comment]
I am still getting a clevel 1 Dunadan ranger with nothing in his house except a scroll WoR.

**Comment by Netbrian** [comment]
> I am still getting a clevel 1 Dunadan ranger with nothing in his house except a scroll WoR.

Hm, I'll investigate this.  Thanks for putting up with me in the meantime.

**Comment by agoodman00** [comment]
> > I am still getting a clevel 1 Dunadan ranger with nothing in his house except a scroll WoR.
> 
> Hm, I'll investigate this. Thanks for putting up with me in the meantime.

haha!  No problem.  Maybe try using a new zip name so you know it created a new one.

**Comment by Netbrian** [comment]
I've been testing the latest release, and it looks like there might still be a problem with the borg accumulating teleport staves, even if he's overweight.

Here's an example!

[Ninwe Tele 2.zip](https://github.com/user-attachments/files/17446967/Ninwe.Tele.2.zip)

**Comment by agoodman00** [comment]
ya, the other case I the code got rid of "extra" staffs when the charges were fewer than the count of staffs.  In this case you have 10 staffs and 24 charges.  I think I need to make that code more complex so it guesses how many charges it will lose when it dumps a staff.  
This is going to take some work.  I will play with it Monday.

**Comment by Netbrian** [comment]
I wonder if the borg should be more aggressive with stashing teleport staves/teleport level scrolls/recharge scrolls at home.  I've noticed he tends to go through them exceptionally fast, and then gets stuck waiting around for stores to restock.

[Ninwe Tele 3.zip](https://github.com/user-attachments/files/17451696/Ninwe.Tele.3.zip)

I realize that this wouldn't be easy to fix, so it's just an aside.

**Comment by agoodman00** [comment]
The problem is, he is pretty aggressive about stocking those at home but he won't stock something in his house if it gives him "power" to carry it around.  Since he isn't clear on what dropping a staff in a stack will do to the charge count, he is making mistakes in calculating if he can drop it, deciding that if he has 10 staffs and 20 charges, well, perhaps if he drops a staff it will be 9 staffs and no charges so he shouldn't ever drop till he has more staffs than charges.  
I think once I recode to make the charge count on dropping staffs more reasonable we can see how he behaves and retool from there.
As far as scrolls, I don't think he stocks recharge scrolls at home. I think he does stock teleport scrolls but he burns through them so fast it doesn't really help.

**Comment by agoodman00** [comment]
we can see if https://github.com/angband/angband/pull/6110 helps

**Comment by Netbrian** [comment]
[Ninwe Potion.zip](https://github.com/user-attachments/files/17469140/Ninwe.Potion.zip)

This is the borg that seems to forget he has staves at home.

**Comment by agoodman00** [comment]
I have hope that my change will help that but I will test tomorrow

**Comment by agoodman00** [comment]
Well, here is one problem... 
            /* Analyze */
            if (item->sval == sv_staff_teleportation) {
                **if (borg.trait[BI_MAXDEPTH] <= 95) {**
                    borg.trait[BI_AESCAPE] += (item->iqty);
                    if (borg_activate_failure(item->tval, item->sval) < 500) {
                        borg.trait[BI_AESCAPE] += item->pval;
                    }
                }
            } else if (item->sval == sv_staff_speed) {
                **if (borg.trait[BI_MAXDEPTH] <= 95)**
                    borg.trait[BI_ASPEED] += item->pval;

Why would staffs of teleport and staffs of speed no longer "count" after  depth 95?!?!?  It's not like the borg stops needing them... And the code has been that way since at least 3.4.0 (the earliest borg codebase I have).  If I remove that check he at least grabs one staff before heading down.  I will take a look at why he isn't grabbing a second.

**Comment by agoodman00** [comment]
oh, he doesn't need a second.  One is enough.  It only seemed like he needed a second because by the time I stopped him he had used a charge and was then down below the requirement. I will check in this fix... make it part of the escape change since that hasnt been merged in yet.

**Comment by agoodman00** [comment]
> Given how quickly the borg goes through teleport usages, are we sure one is enough?

No? 🙂
This is something you could adjust in the borg.txt if you want to experiment and see what you think would work best.  
the problem with making the number too high is that, as you said, he burns through them fast so he will quickly end up with none.

**Comment by Netbrian** [comment]
This is working now!
