### ISSUE TITLE
Borg Traps and Freezing

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6111]
The borg struggles with this gas trap, and the keys eventually unhook.  Not sure what's going on.

[Ninwe Rogue.zip](https://github.com/user-attachments/files/17491234/Ninwe.Rogue.zip)

**Comment by Netbrian** [comment]
@agoodman00

**Comment by backwardsEric** [comment]
It looks like the borg tries to use the activation on the shield to disable the trap.  That activation prompts for a direction, but the borg does not provide one.  The code that has to be changed is around borg-flow.c:908:  would need to work in supplying a direction there but the DISABLE_TRAPS_DESTROY_DOORS spell there does not need a direction - only the item activation does.

**Comment by agoodman00** [comment]
Makes sense.  I added the random artifact activations very recently and this isn’t the first one I messed up  should be relatively easy to fix.

**Comment by agoodman00** [comment]
this should do it.  https://github.com/angband/angband/pull/6112 
since you are playing with random artifacts, let me know if you run into any more issues.

**Comment by Netbrian** [comment]
I tried this with the below save, and the borg just crashed somehow.  Not sure if it's this change or something else.

[Ninwe Crash V01.zip](https://github.com/user-attachments/files/17508765/Ninwe.Crash.V01.zip)

**Comment by agoodman00** [comment]
This crash is fixed in https://github.com/angband/angband/pull/6114

**Comment by Netbrian** [comment]
I noticed the crash happening with non-necromancer characters.  Will this still fix it?

**Comment by agoodman00** [comment]
I really should have checked it in separately but I got lazy... plus I felt stupid because this was EXACTLY the sort of bug I thought might happen with the check in that caused this (the staff charges fix) and I had reread that section of code 3 times and missed it each time.  I should have slowed down and run more tests overnight to make sure it was clean.  I get what I deserve for moving too fast when it was completely unnecessary.
